@startuml SkywalkerServerFramework

class SSFObject
{
    +SSFObject()
    +SSFObject(SSFObjectContext &InContext, SSFObjectErrors &InErrors)
    +virtual ~SSFObject()

    #SSFString ObjectClassName
    #SSFObjectContext ObjectContext

    +{abstract} const std::string &GetObjectClassName()
}

class SSFOModule
{

}

class SSFOModuleManager
{

}

class SSFOPlugin
{

}

class SSFOPluginManager
{

}

class SSFCommandLine
{

}

'继承自 SSFObject
SSFObject <|-- SSFOModule
SSFObject <|-- SSFCommandLine

'继承自 SSFOModule
SSFOModule <|-- SSFOModuleManager

'继承自 SSFOModuleManager
SSFOModuleManager <|-- SSFOPlugin
SSFOModuleManager <|-- SSFOPluginManager

@enduml
