@startuml SkywalkerServerFramework

class SSFObject
{
}

'继承自 SSFObject
SSFObject <|-- SSFOModule
SSFObject <|-- SSFService
class SSFOModule
{

}

class SSFService
{

}

'继承自 SSFOModule
SSFOModule <|-- SSFOModuleManager
class SSFOModuleManager
{

}

'继承自 SSFOModuleManager
SSFOModuleManager <|-- SSFOPlugin
SSFOModuleManager <|-- SSFOPluginManager
class SSFOPlugin
{

}

class SSFOPluginManager
{

}

'继承自 SSFOService
SSFService <|-- SSFFrameworkService
SSFService <|-- SSFLevelService
class SSFFrameworkService
{
}

class SSFLevelService
{
}

'继承自 SSFOFrameworkService
SSFFrameworkService <|-- SSFEventService
class SSFEventService
{

}

@enduml
